-- Motionsalt Compass — finance feature.
--
-- Adds a per-user running balance, a debts/obligations table, and a
-- pending-confirmations table used to gate destructive AI actions on
-- financial data (deleting a debt, overwriting the balance).
--
-- Same conventions as 0001_initial.sql:
--   * ISO-8601 UTC TEXT timestamps
--   * booleans as 0/1 INTEGERs
--   * IDs are AUTOINCREMENT INTEGER
--
-- Money is stored as INTEGER minor units (cents / smallest currency
-- unit) to avoid floating-point drift. The runtime layer converts to
-- and from decimal strings at the edges. There is no per-currency
-- accounting in this iteration — the user tracks one running number.

-- ---------------------------------------------------------------
-- user_balance — a single running balance per user
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_balance (
  user_id     INTEGER PRIMARY KEY,        -- Telegram user id
  amount_cents INTEGER NOT NULL DEFAULT 0, -- current running balance in minor units
  currency    TEXT    NOT NULL DEFAULT 'USD',
  updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ---------------------------------------------------------------
-- debts — things owed, either by the user or that the user is
-- holding money for on behalf of someone else.
--
-- `responsible_party` explicitly models whose obligation this is:
--   'user' — the user's own debt, may be paid from their balance
--   'other' — someone else's debt; the user is only holding/passing
--             money for it and MUST NOT pay it from their own funds
-- The `on_behalf_of` free-text field names that other person when
-- responsible_party = 'other' (e.g. "mom", "roommate").
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS debts (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id            INTEGER NOT NULL,          -- Telegram user id
  creditor           TEXT    NOT NULL,          -- who it's owed to
  amount_cents       INTEGER NOT NULL,          -- outstanding amount in minor units
  currency           TEXT    NOT NULL DEFAULT 'USD',
  responsible_party  TEXT    NOT NULL DEFAULT 'user'
                       CHECK (responsible_party IN ('user','other')),
  on_behalf_of       TEXT,                       -- who the debt actually belongs to (when responsible_party='other')
  due                TEXT,                       -- ISO datetime OR loose text ("end of month"), same pattern as tasks.scheduled_for
  urgency            INTEGER NOT NULL DEFAULT 3, -- 1 highest, 5 lowest (mirrors tasks.priority)
  status             TEXT    NOT NULL DEFAULT 'open'
                       CHECK (status IN ('open','paid','cancelled')),
  note               TEXT,                       -- free-text context
  created_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_debts_user_status
  ON debts (user_id, status);

CREATE INDEX IF NOT EXISTS idx_debts_user_responsible
  ON debts (user_id, responsible_party);

-- ---------------------------------------------------------------
-- pending_confirmations — short-lived tokens for destructive
-- financial actions the agent proposed. The agent creates a row via
-- the request_confirmation tool, tells the user what it's about to
-- do, and only performs the action after the user's next turn
-- affirms it (the agent then calls the corresponding execute-tool
-- with the token).
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pending_confirmations (
  token       TEXT    PRIMARY KEY,        -- opaque short id, generated by the runtime
  user_id     INTEGER NOT NULL,
  action      TEXT    NOT NULL,           -- e.g. 'delete_debt', 'overwrite_balance'
  payload     TEXT    NOT NULL,           -- JSON: the action's arguments
  summary     TEXT    NOT NULL,           -- human-readable description shown to the user
  created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  expires_at  TEXT    NOT NULL            -- ISO-8601 UTC; runtime rejects expired tokens
);

CREATE INDEX IF NOT EXISTS idx_pending_confirmations_user
  ON pending_confirmations (user_id, created_at DESC);
